### ISSUE TITLE
Setup CI/CD for running unit tests and linting rules using GitHub Actions

### ISSUE THREAD

**Issue by lache-melvin** [matai-2021/gardenz#11]
- Run the linting rules on pushes to all branches
- Run linting and unit tests on PRs to `main` and `dev`
- Prevent pushes to `main` and `dev` without a PR in which the linting and unit tests pass

**Comment by bosh-code** [comment]
Github lint action for running eslint: https://github.com/marketplace/actions/lint-action

**Comment by bosh-code** [comment]
deploy script not working: https://stackoverflow.com/questions/41633344/knex-migration-in-postgres-heroku-error-unable-to-acquire-connection

**Comment by bosh-code** [comment]
postgreSQL config in knexfile needs env virables set up
